import { useEffect, useMemo, useState } from "react";

import { resumeTailoringApi } from "./api";
import type { ResumeTailoring, ResumeTailoringState, TailoringAction, TailoringPlan, TailoredBullet } from "./types";

const ACTION_LABELS: Record<TailoringAction, string> = { Keep: "保留", Rewrite: "改写", Add: "新增已确认事实", DeEmphasize: "降低强调", Omit: "省略" };

export function TailoringPrerequisite({ stale, onGoAnalysis }: { stale: boolean; onGoAnalysis: () => void }) {
  return <section className="fit-empty"><span className="eyebrow">针对性简历优化</span><h2>{stale ? "当前匹配分析已过期" : "请先完成岗位匹配分析，再生成针对性简历"}</h2><p>简历优化只使用有效的岗位要求与经历证据，不会自动重新运行匹配分析。</p><button className="primary-link button-link" onClick={onGoAnalysis}>前往匹配分析</button></section>;
}

export function EvidenceDrawer({ bullet, plan }: { bullet: TailoredBullet; plan: TailoringPlan }) {
  const segments = plan.evidence_segments.filter((item) => bullet.evidence_source_ids.includes(item.segment_id));
  const parentIds = new Set([...bullet.evidence_source_ids, ...segments.map((item) => item.parent_source_id)]);
  const evidence = plan.evidence.filter((item) => parentIds.has(item.catalog_id));
  const planItem = plan.experiences.flatMap((item) => item.bullet_items).find((item) => item.plan_item_id === bullet.plan_item_id);
  const requirements = plan.relevant_requirements.filter((item) => bullet.requirement_ids.includes(item.requirement_id));
  const context = planItem?.context_metadata;
  return <details className="evidence-drawer"><summary>查看依据</summary><div><h4>支持内容</h4>{segments.map((item) => <article key={item.segment_id}><span>{item.segment_id} · 来源 {item.parent_source_id}</span><p>{item.text}</p></article>)}{segments.length === 0 && evidence.map((item) => <article key={item.catalog_id}><span>{item.source_type} · {item.catalog_id}</span><p>{item.text}</p></article>)}<h4>经历背景</h4>{context && <p>{[context.experience_title, context.organization, context.project_name, context.date_range].filter(Boolean).join(" · ")}</p>}<h4>对应岗位要求</h4>{requirements.map((item) => <p key={item.requirement_id}>{item.importance} · {item.text}</p>)}<h4>校验结果</h4><ul><li>证据引用：{bullet.validation.references_valid ? "通过" : "未通过"}</li><li>数字真实性：{bullet.validation.numbers_valid ? "通过" : "未通过"}</li><li>技能真实性：{bullet.validation.skills_valid ? "通过" : "未通过"}</li><li>职责边界：{bullet.validation.ownership_valid ? "通过" : "未通过"}</li><li>实体信息：{bullet.validation.entities_valid ? "通过" : "未通过"}</li><li>语义支持：{bullet.validation.semantic_supported ? "通过" : "待确认或未通过"}</li></ul></div></details>;
}

export function TailoringPlanView({ tailoring, busy, onGenerate }: { tailoring: ResumeTailoring; busy: boolean; onGenerate: (items: { plan_item_id: string; action: TailoringAction; omit_confirmed: boolean }[]) => void }) {
  const [actions, setActions] = useState<Record<string, TailoringAction>>({});
  const [omitConfirmed, setOmitConfirmed] = useState<Record<string, boolean>>({});
  const items = tailoring.tailoring_plan.experiences.flatMap((experience) => experience.bullet_items);
  return <div className="tailoring-plan"><section className="fit-card"><span className="card-kicker">简历优化方案</span><h2>先确认要突出什么</h2><p>方案只使用当前岗位要求与已验证的经历证据；确认前不会调用 AI。</p></section>{tailoring.tailoring_plan.experiences.map((experience) => <section className="fit-card" key={experience.experience_id}><div className="tailoring-heading"><div><h2>{experience.title}</h2><p>{experience.organization}{experience.date_range ? ` · ${experience.date_range}` : ""}</p></div><strong>{experience.coverage_summary}</strong></div>{experience.bullet_items.map((item) => { const action = actions[item.plan_item_id] || item.effective_action; return <article className="plan-bullet" key={item.plan_item_id}><p>{item.original_text}</p><label>建议操作<select value={action} onChange={(event) => setActions((value) => ({ ...value, [item.plan_item_id]: event.target.value as TailoringAction }))}>{Object.entries(ACTION_LABELS).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>{action === "Omit" && <label className="omit-confirm"><input type="checkbox" checked={Boolean(omitConfirmed[item.plan_item_id])} onChange={(event) => setOmitConfirmed((value) => ({ ...value, [item.plan_item_id]: event.target.checked }))} />我明确确认省略这条真实经历</label>}<small>{item.reason}</small></article>; })}</section>)}{tailoring.tailoring_plan.unsupported_requirements.length > 0 && <section className="unsupported-requirements"><h2>当前没有可支持的岗位要求</h2><p>不建议通过措辞包装以下要求：</p><ul>{tailoring.tailoring_plan.unsupported_requirements.map((item) => <li key={item.requirement_id}>{item.text}</li>)}</ul></section>}<button className="primary-link button-link" disabled={busy} onClick={() => onGenerate(items.map((item) => ({ plan_item_id: item.plan_item_id, action: actions[item.plan_item_id] || item.effective_action, omit_confirmed: Boolean(omitConfirmed[item.plan_item_id]) })))}>{busy ? "正在生成并验证…" : "确认方案并生成简历草稿"}</button></div>;
}

function BulletReview({ bullet, plan, busy, onEdit, onKeep }: { bullet: TailoredBullet; plan: TailoringPlan; busy: boolean; onEdit: (id: string, text: string) => void; onKeep: (id: string) => void }) {
  const [editing, setEditing] = useState(false); const [text, setText] = useState(bullet.tailored_text);
  const kept = bullet.change_kind === "ModelKeep" || bullet.change_kind === "FormattingOnlyKeep" || bullet.change_kind === "PlanKeep";
  const status = bullet.change_kind === "ModelKeep" ? "原内容已经较适合该岗位，建议保留" : bullet.change_kind === "FormattingOnlyKeep" ? "未发现有价值的实质改写，已保留原文" : bullet.change_kind === "PlanKeep" ? "优化方案建议保留原内容" : bullet.state === "Validated" ? "已验证的针对性改写" : bullet.state === "Unverified" ? "用户编辑，尚未验证" : bullet.state === "FallbackOriginal" ? "验证失败，已保留原文" : "保留原文";
  return <article className={`tailored-bullet state-${bullet.state.toLowerCase()}`}><div className={kept ? "kept-bullet" : "before-after"}><div><span>原内容</span><p>{bullet.original_text}</p></div>{!kept && <div><span>建议修改</span>{editing ? <textarea value={text} onChange={(event) => setText(event.target.value)} rows={4} /> : <p>{bullet.tailored_text}</p>}</div>}</div><div className="bullet-review-actions"><span>{status}</span>{!kept && (editing ? <button disabled={busy} onClick={() => { onEdit(bullet.plan_item_id, text); setEditing(false); }}>保存编辑</button> : <button onClick={() => setEditing(true)}>编辑</button>)}{!kept && <button disabled={busy} onClick={() => onKeep(bullet.plan_item_id)}>保留原文</button>}</div>{bullet.validation.violations.map((item) => <p className="validation-warning" key={item}>{item}</p>)}<EvidenceDrawer bullet={bullet} plan={plan} /></article>;
}

export function TailoredDraftView({ tailoring, busy, onEdit, onKeep, onValidate, onAccept, onRefreshPlan }: { tailoring: ResumeTailoring; busy: boolean; onEdit: (id: string, text: string) => void; onKeep: (id: string) => void; onValidate: () => void; onAccept: () => void; onRefreshPlan: () => void }) {
  const draft = tailoring.user_edited_draft || tailoring.generated_draft;
  if (!("experiences" in draft)) return null;
  const pending = draft.experiences.some((experience) => experience.bullets.some((bullet) => bullet.state === "Unverified"));
  return <div className="tailored-draft">{tailoring.is_stale && <div className="stale-notice"><strong>当前简历优化已过期</strong><span>可以查看，但必须刷新方案后才能接受。</span><button disabled={busy} onClick={onRefreshPlan}>刷新简历优化方案</button></div>}<section className="fit-card"><span className="card-kicker">已验证的简历草稿</span><h2>原内容与针对性改写</h2><p>{draft.summary}</p><div className="draft-actions">{pending && <button disabled={busy} onClick={onValidate}>验证改写</button>}<button className="primary-link button-link" disabled={busy || tailoring.is_stale || pending || tailoring.status === "ValidationFailed"} onClick={onAccept}>{tailoring.status === "Accepted" ? "已接受" : "接受这份简历草稿"}</button></div></section>{draft.experiences.map((experience) => <section className="fit-card" key={experience.experience_id}><h2>{experience.title}</h2><p>{experience.organization} · {experience.date_range}</p>{experience.bullets.map((bullet) => <BulletReview key={bullet.plan_item_id} bullet={bullet} plan={tailoring.tailoring_plan} busy={busy} onEdit={onEdit} onKeep={onKeep} />)}</section>)}</div>;
}

export default function ResumeTailoringPanel({ jobId, onGoAnalysis }: { jobId: number; onGoAnalysis: () => void }) {
  const [state, setState] = useState<ResumeTailoringState | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; resumeTailoringApi.get(jobId).then((value) => { if (active) setState(value); }).catch((cause: Error) => { if (active) setError(cause.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [jobId]);
  async function run(action: () => Promise<ResumeTailoringState>) { setBusy(true); setError(""); try { setState(await action()); } catch (cause) { setError(cause instanceof Error ? cause.message : "简历优化失败。"); } finally { setBusy(false); } }
  const tailoring = state?.tailoring; const draftReady = useMemo(() => Boolean(tailoring && Object.keys(tailoring.generated_draft).length), [tailoring]);
  if (loading) return <section className="fit-loading"><span className="spinner dark" />正在读取简历优化…</section>;
  if (error && !state) return <section className="fit-empty"><span className="eyebrow">针对性简历优化</span><h2>暂时无法读取简历优化</h2><p className="error" role="alert">{error}</p></section>;
  if (state?.prerequisite !== "Ready") return <TailoringPrerequisite stale={state?.prerequisite === "AnalysisStale"} onGoAnalysis={onGoAnalysis} />;
  return <>{error && <div className="error" role="alert">{error}</div>}{!tailoring && <section className="fit-empty"><span className="eyebrow">针对性简历优化</span><h2>先生成可检查的优化方案</h2><p>系统只选择已有真实证据，生成方案时不会调用 AI。</p><button className="primary-link button-link" disabled={busy} onClick={() => void run(() => resumeTailoringApi.createPlan(jobId))}>{busy ? "正在生成方案…" : "生成简历优化方案"}</button></section>}{tailoring && !draftReady && tailoring.is_stale && <section className="fit-empty"><h2>当前简历优化方案已过期</h2><p>证据与验证边界已更新，请刷新方案后继续。</p><button className="primary-link button-link" disabled={busy} onClick={() => void run(() => resumeTailoringApi.createPlan(jobId))}>刷新简历优化方案</button></section>}{tailoring && !draftReady && !tailoring.is_stale && <TailoringPlanView tailoring={tailoring} busy={busy} onGenerate={(items) => void run(async () => { await resumeTailoringApi.patchPlan(jobId, { items, confirmed: true }); return resumeTailoringApi.generateDraft(jobId); })} />}{tailoring && draftReady && <TailoredDraftView tailoring={tailoring} busy={busy} onEdit={(id, text) => void run(() => resumeTailoringApi.editDraft(jobId, [{ plan_item_id: id, text }]))} onKeep={(id) => void run(() => resumeTailoringApi.editDraft(jobId, [{ plan_item_id: id, text: "保留原文", keep_original: true }]))} onValidate={() => void run(() => resumeTailoringApi.validate(jobId))} onAccept={() => void run(() => resumeTailoringApi.accept(jobId))} onRefreshPlan={() => void run(() => resumeTailoringApi.createPlan(jobId))} />}</>;
}
